### PR TITLE
Task-3: First API with AWS API Gateway and AWS Lambda

### PR DESCRIPTION
**Pull request by dmytro-shershnev1**

### CODE REVIEW

**Comment by viktordavidovich** [comment]
Nothing has been done from acceptance criteria point of view.

**Comment by dmytro-shershnev1** [comment]
> Nothing has been done from acceptance criteria point of view.

It's just placeholder that will be updated soon with real commit.

**Comment by viktordavidovich** [comment]
> > Nothing has been done from acceptance criteria point of view.
> 
> It's just placeholder that will be updated soon with real commit.

I see. Please, let me know when it's ready for review. 
Thanks!

**Comment by dmytro-shershnev1** [comment]
> > > Nothing has been done from acceptance criteria point of view.
> > 
> > 
> > It's just placeholder that will be updated soon with real commit.
> 
> I see. Please, let me know when it's ready for review. Thanks!

Sure, thanks!

**Comment by dmytro-shershnev1** [comment]
@viktordavidovich  It's can be reviewed now. This PR also will be updated with Unit Tests, Swagger and FE repository as well.

**Review by viktordavidovich — APPROVED** [review]
Well done! 
All the AC's from the minimal task requirements passed successfully. 
While not all the additional tasks has been implemented as of now. 

**Extra task:** _+1 - Webpack is configured for Product Service_
**Result**: +0 Webpack configuration is missing.

**Extra task:** _+1 (All languages) - SWAGGER documentation is created for Product Service_
**Result:** +0 Swagger is missing.

**Extra task**: _+1 (All languages) - Lambda handlers are covered by basic UNIT tests (NO infrastructure logic is needed to be covered)_
**Result**: +0 There are no UNIT tests.

**Extra task**: _+1 (All languages) - Main error scenarios are handled by API ("Product not found" error)._
**Result**: +0 No extra scenarios has been implemented. 

**Summary:** 
Max score for this task is 11, but I can give you only 7.

Please, let me know when it's done, I will do review and update final score.

**Comment by dmytro-shershnev1** [comment]
> **Extra task:** _+1 - Webpack is configured for Product Service_ **Result**: +0 Webpack configuration is missing.
> 
Related to this option I think it's not relevant in my case because new version of serverless `aws-nodejs-typescript` template store serverless configuration as `serverless.ts` so in this case `webpack` configuration useless because it's already there. I will post this question addressed to ur lectors in Teams chat.

**Comment by dmytro-shershnev1** [comment]
> Well done! All the AC's from the minimal task requirements passed successfully. While not all the additional tasks has been implemented as of now.
> 
> **Extra task:** _+1 - Webpack is configured for Product Service_ **Result**: +0 Webpack configuration is missing.
> 
> **Extra task:** _+1 (All languages) - SWAGGER documentation is created for Product Service_ **Result:** +0 Swagger is missing.
> 
> **Extra task**: _+1 (All languages) - Lambda handlers are covered by basic UNIT tests (NO infrastructure logic is needed to be covered)_ **Result**: +0 There are no UNIT tests.
> 
> **Extra task**: _+1 (All languages) - Main error scenarios are handled by API ("Product not found" error)._ **Result**: +0 No extra scenarios has been implemented.
> 
> **Summary:** Max score for this task is 11, but I can give you only 7.
> 
> Please, let me know when it's done, I will do review and update final score.

@viktordavidovich 
All evaluation criteria has been done. `Webpack` config do not required at all for this `aws-nodejs-typescript` template.

**Pull request merged**
